[package]
name = "spiro-server"
version = "0.1.0"
authors = ["Rico Huijbers <rix0rrr@gmail.com>", "Caleb Jones <code@calebjones.net>"]

[dependencies]
futures = "*"
tokio-core = "*"
conrod = "0.44.1"
piston_window = "0.52.0"
